### ISSUE TITLE
TYPO: Abstract submission confirmation says "You most also ..." (should be "must")

### ISSUE THREAD

**Issue by HenrikBengtsson** [user2016/user2016.github.io#51]
After submitting an abstract, you get to confirmation page http://user2016.org/abstract-submission/index.html saying:

> Thanks <First Name>!
> 
> We have received your submission and also sent you a confirmation email. The program committee will be in touch once decisions have been made. Please note that submission does not guarantee acceptance.
> 
> You **most** also register for the conference separately if you have not done so already: https://app.certain.com/profile/form/index.cfm?PKformID=0x2049265f7bc

Note it says: "most" but should be "must".

**Comment by karthik** [comment]
Fixed, thanks @HenrikBengtsson
